# Generated by Django 4.2.16 on 2024-10-17 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_watchlist_auction_alter_watchlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='id',
            field=models.AutoField(auto_created=True, default=False, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
