# Generated by Django 4.2.16 on 2024-10-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist_id_alter_watchlist_auction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('auction', 'user')},
        ),
    ]
